[project]
name = "amnezia-api"
version = "0.0.1"
description = "An API backend for AmneziaVPN containers."
dependencies = [
    "flask",
    "docker"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
